iiwa14_action_server: # NOTE: This must match the node name that loads the parameters
  ros__parameters:
  
    # These are for the RobotLibrary::Control class(es):
    cartesian_damping: [ 5.0, 00.0, 00.0, 00.0, 00.0, 00.0,
                        00.0,  5.0, 00.0, 00.0, 00.0, 00.0,
                        00.0, 00.0,  5.0, 00.0, 00.0, 00.0,
                        00.0, 00.0, 00.0,  1.0, 00.0, 00.0,
                        00.0, 00.0, 00.0, 00.0,  1.0, 00.0,
                        00.0, 00.0, 00.0, 00.0, 00.0,  1.0]
                        
    cartesian_stiffness: [50.0, 00.0, 00.0, 00.0, 00.0, 00.0,
                          00.0, 50.0, 00.0, 00.0, 00.0, 00.0,
                          00.0, 00.0, 50.0, 00.0, 00.0, 00.0,
                          00.0, 00.0, 00.0,  1.0, 00.0, 00.0,
                          00.0, 00.0, 00.0, 00.0,  1.0, 00.0,
                          00.0, 00.0, 00.0, 00.0, 00.0,  1.0]
    frequency: 500.0
    joint_position_gain: 50.0
    joint_velocity_gain: 1.0
    manipulability_threshold: 0.001
    
    # This is for the underlying QP solver class:
    solver_initial_barrier: 100.0
    solver_reduction_rate: 0.01
    max_steps: 5
